package state

import (
	"mapp-game-go/internal/faction"
	"mapp-game-go/internal/world"
)

// ActiveHistoricalTradeFlows returns the scenario-defined historical flows
// active in the current year. The flow remains active independently of the
// survival of any faction; only the current owner of a real endpoint receives
// its income.
func (s *GameState) ActiveHistoricalTradeFlows() []world.HistoricalTradeFlow {
	if s == nil || len(s.TradeCenters.HistoricalFlows) == 0 {
		return nil
	}
	flows := make([]world.HistoricalTradeFlow, 0, len(s.TradeCenters.HistoricalFlows))
	for _, flow := range s.TradeCenters.HistoricalFlows {
		if flow.ActiveInYear(s.Year) && s.historicalFlowCentersActive(flow) {
			flows = append(flows, flow)
		}
	}
	return flows
}

// HistoricalTradeFlowAmount returns the active amount after competition from
// newly opened historical centers has reduced the old route's capacity.
func (s *GameState) HistoricalTradeFlowAmount(flow world.HistoricalTradeFlow) int {
	amount := flow.AmountPerTurn
	if amount <= 0 {
		return 0
	}
	for _, center := range s.TradeCenters.Centers {
		if !center.ActiveInYear(s.Year) {
			continue
		}
		for _, impact := range center.CompetitionImpacts {
			if impact.CenterID != flow.FromRegionID && impact.CenterID != flow.ToRegionID {
				continue
			}
			amount = applyHistoricalPercent(amount, impact.AmountPercent)
		}
	}
	return amount
}

// HistoricalTradeFlowIncome returns the active gold income after competition
// from newly opened historical centers has reduced the old route's return.
func (s *GameState) HistoricalTradeFlowIncome(flow world.HistoricalTradeFlow) int {
	income := flow.GoldIncomePerTurn
	if income <= 0 {
		return 0
	}
	for _, center := range s.TradeCenters.Centers {
		if !center.ActiveInYear(s.Year) {
			continue
		}
		for _, impact := range center.CompetitionImpacts {
			if impact.CenterID == flow.FromRegionID || impact.CenterID == flow.ToRegionID {
				income = applyHistoricalPercent(income, impact.IncomePercent)
			}
		}
	}
	return income
}

func applyHistoricalPercent(value, percent int) int {
	if percent == 0 {
		return value
	}
	if percent < -100 {
		percent = -100
	}
	if percent > 200 {
		percent = 200
	}
	value = value * (100 + percent) / 100
	if value < 0 {
		return 0
	}
	return value
}

func (s *GameState) historicalFlowCentersActive(flow world.HistoricalTradeFlow) bool {
	for _, id := range []world.RegionID{flow.FromRegionID, flow.ToRegionID} {
		for _, center := range s.TradeCenters.Centers {
			if center.ID == id {
				if !center.ActiveInYear(s.Year) {
					return false
				}
				break
			}
		}
	}
	return true
}

// HistoricalTradeIncomeForFaction returns the gold generated by active
// historical flows for the current owner of their real endpoints. A flow
// touching one real endpoint pays that endpoint in full; a flow between two
// real endpoints is split evenly, with the remainder assigned deterministically
// to the first endpoint.
func (s *GameState) HistoricalTradeIncomeForFaction(fid faction.FactionID) int {
	if s == nil || fid == "" {
		return 0
	}
	income := 0
	for _, flow := range s.ActiveHistoricalTradeFlows() {
		incomePerTurn := s.HistoricalTradeFlowIncome(flow)
		if incomePerTurn <= 0 {
			continue
		}
		from := s.Regions[flow.FromRegionID]
		to := s.Regions[flow.ToRegionID]
		fromOwner := historicalEndpointOwner(s, from)
		toOwner := historicalEndpointOwner(s, to)
		if fromOwner == fid && toOwner == fid {
			income += incomePerTurn
			continue
		}
		if fromOwner != "" && toOwner != "" {
			share := incomePerTurn / 2
			if incomePerTurn%2 != 0 && string(flow.FromRegionID) < string(flow.ToRegionID) {
				share++
			}
			if fromOwner == fid || toOwner == fid {
				income += share
			}
			continue
		}
		if fromOwner == fid || toOwner == fid {
			income += incomePerTurn
		}
	}
	return income
}

func historicalEndpointOwner(s *GameState, region *world.Region) faction.FactionID {
	if s == nil || region == nil || region.IsSea || region.IsTerrainArea || region.OwnerID == "" {
		return ""
	}
	fid := faction.FactionID(region.OwnerID)
	if owner := s.Factions[fid]; owner == nil || owner.IsEliminated {
		return ""
	}
	return fid
}
