package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

func main() {
	version := gitOutput("describe", "--tags", "--always")
	commit := gitOutput("rev-parse", "--short", "HEAD")
	if version == "" {
		version = "dev"
	}
	if commit == "" {
		commit = "unknown"
	}
	date := time.Now().UTC().Format(time.RFC3339)

	src := fmt.Sprintf(`package buildinfo

// Code generated by go generate; DO NOT EDIT.

func init() {
	Version = %q
	Commit = %q
	Date = %q
}
`, version, commit, date)

	formatted, err := format.Source([]byte(src))
	if err != nil {
		fatalf("formatting generated source: %v", err)
	}

	outPath := filepath.Join("generated.go")
	if existing, err := os.ReadFile(outPath); err == nil {
		if bytes.Equal(existing, formatted) {
			return
		}
	}
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		fatalf("writing %s: %v", outPath, err)
	}
}

func gitOutput(args ...string) string {
	cmd := exec.Command("git", args...)
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}

func fatalf(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
